### ISSUE TITLE
Pokemon in "Caught" are not in order.

### ISSUE THREAD

**Issue by t-mathis** [Stalruth/porysearch#6]
Pokemon added from the Pokemon tab into "Caught" are not in order. Not sure if bug... or a feature. 

Here are the steps I took to do this:
1) Refresh the page.
2) Add Charizard, Charmeleon, then Charmander.
3) Validate that the "Caught" tab added the 3 Pokemon. (It showed 6, then 5, then 4.)
4) Refresh the page, and check again. (It showed 6, then 5, then 4.)

![porysearch_bug_2](https://cloud.githubusercontent.com/assets/5705310/5343767/e063f80a-7ebd-11e4-94f7-c863ef1b927a.png)

**Comment by Stalruth** [comment]
Thanks for reporting!
I'll work on this tomorrow.  I'll probably use an insertion sort to put them in the right order.
(this will mess up the function with people who were using it before, but IMO its worth sorting these things.)

**Comment by t-mathis** [comment]
That's a good sorting algorithm to use since it will almost always be nearly-sorted anyways, making it super fast.

**Comment by Stalruth** [comment]
This'll be solved defining a comparator attribute for the CaughtPokemons collection.
This feature of backbone uses an insertion sort to ensure the list is always nearly-sorted, and saves me the trouble of writing/maintaining one of my own.

I have it working on my local machine, but only on refresh.  I'm currently working to get the table to update as pokemon are added.
